version: '3.7'

services:

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    ports:
      - "8090:8080"
    environment:
      DB_PORT: 5433
      DB_USER: keyloack
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - oath-keycloak
    depends_on:
      - database-keycloack


  database-keycloack:
    image: postgres:14.2
    container_name: database-keycloack
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=keyloack
      - POSTGRES_USER=keyloack
      - POSTGRES_PASSWORD=password
    volumes:
      - oath-keycloak-volume:/var/lib/postgresql/data/

volumes:
  oath-keycloak-volume:

networks:
  oath-keycloak:
