version: '3.7'

services:

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin